"""
Plot parameter estimates of care seeking alongside prevalence: Fig 3 in manuscript

If updates are needed:
    1. Make required updates to the model (model.py) or data folder
    2. Run run_calibration to generate the files 'results/zim_sti_calib_stats_treat*.obj'
    3. Run run_plot_data.py to generate the epi result files:
        results/zim_sti_calib_df.obj
        results/zim_sti_calib_res.obj
        results/zim_sti_care_seeking.obj
    4. Run this script to generate the figure

"""

# Import packages
import sciris as sc
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as pl
from utils import set_font


# %% Run as a script
if __name__ == '__main__':

    show = False

    # Load dataframes - these are generated by run_calibration.py
    parfolder = 'results'
    resfolder = 'results'
    df = sc.loadobj(f'{parfolder}/zim_sti_calib_df.obj')
    cs_df = sc.loadobj(f'{parfolder}/zim_sti_care_seeking.obj')
    results = sc.loadobj(f'{resfolder}/zim_sti_calib_res.obj')

    # clist = sc.vectocolor([.5, .8, 1])
    clist = sc.gridcolors(3)
    # clist = [clist[0], clist[1], clist[2]]
    colors = sc.objdict(treat50=clist[0], treat80=clist[1], treat100=clist[2])

    set_font(size=20)
    fig, axes = pl.subplots(2, 3, figsize=(20, 8))
    axes = axes.ravel()
    ai = 0

    # Plot symptomatic proportion
    ax = axes[ai]
    thisdf = df.loc[df['par'] == 'p_symp'].copy()
    thisdf['value'] *= 100
    sns.boxplot(data=thisdf, x="disease", y="value", hue="scenario", palette=clist, ax=ax)
    ax.set_title('Symptomatic share (F):\n% cases in women accompanied by VDS')
    ax.set_xlabel('')
    ax.set_ylabel('')
    ax.set_ylim(0, 100)
    # Turn off frame around legend
    ax.legend(frameon=False, prop={'size': 16})
    ai += 1

    # Plot symptomatic proportion
    ax = axes[ai]
    cs_df['p_symp_care'] *= 100
    ax = sns.boxplot(data=cs_df, hue="scenario", y="p_symp_care", palette=clist, ax=ax)
    ax.set_title('Care-seeking share (F):\n% women with VDS who seek care')
    ax.set_xlabel('')
    ax.set_ylabel('')
    ax.set_ylim(0, 100)
    ax.get_legend().set_visible(False)
    ai += 1

    # Plot overall proportion treated
    ax = axes[ai]
    thisdf = df.loc[df['par'] == 'p_treat'].copy()
    thisdf['value'] *= 100
    ax = sns.boxplot(data=thisdf, x="disease", y="value", hue="scenario", palette=clist, ax=ax)
    ax.set_title('Treated share (F):\n% cases in women that are treated')
    ax.set_xlabel('')
    ax.set_ylabel('')
    ax.set_ylim(bottom=0)
    ax.get_legend().set_visible(False)
    ai += 1

    # Plot prevalence
    diseases = ['ng', 'ct', 'tv']
    t = results['time']
    start_year = 2010
    end_year = 2025
    si = sc.findfirst(t, start_year)
    ei = sc.findfirst(t, end_year)
    sti_data = pd.read_csv(f'data/zimbabwe_sti_data_plot.csv')
    sti_data = sti_data.loc[(sti_data.time >= start_year) & (sti_data.time <= end_year)]

    for i, disease in enumerate(diseases):
        ax = axes[i+3]

        for scenario in ['treat50', 'treat80', 'treat100']:
            res = results[scenario]
            prevalence = np.array([r[disease+'_prevalence'] for r in res])
            ax.plot(t[si:ei], prevalence.transpose()[si:ei, :]*100, alpha=0.6, lw=0.5, label=scenario, color=colors[scenario])
            # ax.scatter(sti_data.time, sti_data[disease+'_prevalence']*100, color='k', label='Data')

        ax.set_title(disease.upper()+' prevalence (%)')
        ax.set_ylim(bottom=0)
        ax.set_ylabel('')
        ax.set_xlabel('')

    fig.tight_layout()

    pl.figtext(0.02, 0.92, 'A', fontsize=40, ha='center', va='center')
    pl.figtext(0.35, 0.92, 'B', fontsize=40, ha='center', va='center')
    pl.figtext(0.69, 0.92, 'C', fontsize=40, ha='center', va='center')
    pl.figtext(0.02, 0.45, 'D', fontsize=40, ha='center', va='center')
    pl.figtext(0.35, 0.45, 'E', fontsize=40, ha='center', va='center')
    pl.figtext(0.69, 0.45, 'F', fontsize=40, ha='center', va='center')

    pl.savefig(f"figures/fig3_pars.png", dpi=100)
    if show:
        pl.show()

    print('Done.')
