"""
Plot parameter estimates of care seeking alongside prevalence
Requires running run_calibration first to generate the files
'results/zim_sti_calib_{scenario}.obj' for each scenario.
'make_df' creates a big dataframe from the results, and 'plot_pars' plots it.
"""

# Import packages
import sciris as sc
import pylab as pl
import numpy as np
import pandas as pd
from utils import set_font
import seaborn as sns


# %% Run as a script
if __name__ == '__main__':

    # Load dataframes - these are generated by run_calibration.py
    df = sc.loadobj('results/zim_sti_calib_df.obj')
    results = sc.loadobj('results/zim_sti_calib_res.obj')
    cs_df = sc.loadobj('results/zim_sti_care_seeking.obj')

    # clist = sc.vectocolor([.5, .8, 1])
    clist = sc.gridcolors(3)
    clist = [clist[0], clist[1], clist[2]]
    colors = sc.objdict(treat50=clist[0], treat80=clist[1], treat100=clist[2])

    set_font(size=20)
    fig, axes = pl.subplots(2, 3, figsize=(20, 8))
    axes = axes.ravel()
    ai = 0

    # Plot symptomatic proportion
    ax = axes[ai]
    thisdf = df.loc[df['par'] == 'p_symp']
    thisdf['value'] = thisdf['value']*100
    sns.boxplot(data=thisdf, x="disease", y="value", hue="scenario", palette=clist, ax=ax)
    ax.set_title('Symptomatic share (F):\n% cases in women accompanied by VDS')
    ax.set_xlabel('')
    ax.set_ylabel('')
    ax.set_ylim(0, 100)
    # Turn off frame around legend
    ax.legend(frameon=False, prop={'size': 16})
    ai += 1

    # Plot symptomatic proportion
    ax = axes[ai]
    cs_df['p_symp_care'] = cs_df['p_symp_care']*100
    ax = sns.boxplot(data=cs_df, hue="scenario", y="p_symp_care", palette=clist, ax=ax)
    ax.set_title('Care-seeking share (F):\n% women with VDS who seek care')
    ax.set_xlabel('')
    ax.set_ylabel('')
    ax.set_ylim(0, 100)
    ax.get_legend().set_visible(False)
    ai += 1

    # Plot overall proportion treated
    ax = axes[ai]
    thisdf = df.loc[df['par'] == 'p_treat']
    thisdf['value'] = thisdf['value']*100
    ax = sns.boxplot(data=thisdf, x="disease", y="value", hue="scenario", palette=clist, ax=ax)
    ax.set_title('Treated share (F):\n% cases in women that are treated')
    ax.set_xlabel('')
    ax.set_ylabel('')
    ax.set_ylim(bottom=0)
    ax.get_legend().set_visible(False)
    ai += 1

    # Plot prevalence
    diseases = ['ng', 'ct', 'tv']
    t = results['treat50'][0]['time']
    si = sc.findfirst(t, 2010)
    ei = sc.findfirst(t, 2025)

    for i, disease in enumerate(diseases):
        ax = axes[i+3]

        for scenario in ['treat50', 'treat80', 'treat100']:
            res = results[scenario]
            prevalence = np.array([r[disease+'_prevalence'] for r in res])
            ax.plot(t[si:ei], prevalence.transpose()[si:ei, :]*100, alpha=0.6, lw=0.5, label=scenario, color=colors[scenario])

        ax.set_title(disease.upper()+' prevalence (%)')
        ax.set_ylim(bottom=0)
        ax.set_ylabel('')
        ax.set_xlabel('')

    fig.tight_layout()
    pl.savefig(f"figures/fig3_pars.png", dpi=100)

    print('Done.')
