"""
After running the calibrations on the VMs, run this script on the VMs to generate the files
used for creating figures 2 and 3 in the paper.
All the files generated by this script can be added to the repository.
"""


# %% Imports and settings
import sciris as sc
import pandas as pd
import utils as ut
from model import run_msim, save_stats


if __name__ == '__main__':

    # Settings
    sc.heading('Saving plot files')

    to_run = [
        'fig2',  # Epi stats - requires running the model with the calibration pars
        'fig3',  # STI calibration pars
    ]
    if 'fig2' in to_run:
        sims = run_msim(scenarios=ut.scenarios, use_calib=True, seed=1, debug=False, do_save=True)
        save_stats(sims)

    if 'fig3' in to_run:
        dfs = sc.autolist()
        cs_dfs = sc.autolist()  # care seeking for VDS - not by disease
        results = sc.objdict()
        for scenario in ut.scenarios:
            calib = sc.loadobj(f'results/zim_sti_calib_{scenario}.obj')
            df = calib.df[:500]
            df['scenario'] = ut.scenlabels[scenario]
            df['ng_p_treat'] = df['ng_p_symp']*df['p_symp_care']*int(scenario.strip('treat'))/100
            df['ct_p_treat'] = df['ct_p_symp']*df['p_symp_care']*int(scenario.strip('treat'))/100
            df['tv_p_treat'] = df['tv_p_symp']*df['p_symp_care']*int(scenario.strip('treat'))/100

            df = df.loc[:, df.columns != 'p_symp_care']
            cs_df = calib.df[:500].loc[:, calib.df.columns.isin(['index', 'p_symp_care'])]
            cs_df['scenario'] = scenario
            dfs += df
            cs_dfs += cs_df

            # Save results
            results[scenario] = []  # calib.sim_results[:50]
            reskeys = [f'{dis}_prevalence' for dis in ['ng', 'ct', 'tv']]
            reskeys += [f'{dis}_incidence' for dis in ['ng', 'ct', 'tv']]
            for i in range(50):
                thisdict = {k: calib.sim_results[i][k] for k in reskeys}
                results[scenario].append(thisdict)
            results['time'] = calib.sim_results[0]['time']

        df = pd.concat(dfs)
        cs_df = pd.concat(cs_dfs)

        # Melt dataframe to long form
        vars = ['ng_p_symp', 'ct_p_symp', 'tv_p_symp', 'ng_p_treat', 'ct_p_treat', 'tv_p_treat']
        dfm = df.melt(id_vars=['index', 'mismatch', 'scenario'], value_vars=vars, var_name='variable', value_name='value')

        # Add column for disease
        dfm['disease'] = dfm['variable'].apply(lambda x: x.split('_')[0].upper())
        dfm['par'] = dfm['variable'].apply(lambda x: x[3:])

        # Save results for figure 3
        sc.saveobj('results/zim_sti_calib_df.obj', dfm)
        sc.saveobj('results/zim_sti_care_seeking.obj', cs_df)
        sc.saveobj('results/zim_sti_calib_res.obj', results)

    print('Done!')


